import { StyleSheet } from 'react-native';
import colors from './colors'


const styles = StyleSheet.create({

  singleContact: {
    backgroundColor: colors.white,
    width: '90%',
    height: 70,
    position: 'relative',
    marginLeft: '5%',
    marginRight: '5%',
    padding: 5,
    marginBottom: 3,
    borderRadius: 5,
    shadowColor: colors.shadow,
    shadowOffset: {width: 3, height: 3},
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 2,
  },
  whiteBigContainer: {
    backgroundColor: colors.white,
    width: '90%',
    height: 60,
    position: 'relative',
    marginTop: 5,
    marginBottom: 3,
    marginLeft: '5%',
    marginRight: '5%',
    justifyContent: 'center',
    borderRadius: 1,
    shadowColor: colors.shadow,
    shadowOffset: {width: 3, height: 3},
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 2,
  },
  white_Left_Container: {
    backgroundColor: colors.white,
    width: '40%',
    height: 70,
    position: 'absolute',
    marginRight: '5%',
    marginTop: 5,
    left: '5%',
    justifyContent: 'flex-end',
    borderRadius: 1,
    shadowColor: colors.shadow,
    shadowOffset: {width: 3, height: 3},
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 2,
  },
  white_Right_Container: {
    backgroundColor: colors.white,
    width: '40%',
    height: 70,
    position: 'absolute',
    marginLeft: '5%',
    marginTop: 5,
    justifyContent: 'flex-end',
    right: '5%',
    borderRadius: 1,
    shadowColor: colors.shadow,
    shadowOffset: {width: 3, height: 3},
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 2,

  },

  greyMedium_Container: {
    backgroundColor: colors.white,
    width: '90%',
    height: 50,
    position: 'relative',
    marginTop: 5,
    marginBottom: 3,
    padding:'5%',
    // marginLeft: '5%',
    // marginRight: '5%',
    justifyContent: 'center',
    borderRadius: 5,
    shadowColor: colors.shadow,
    shadowOffset: {width: 3, height: 3},
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 2,
    margin: 3
  },
  mailContainer: {
    backgroundColor: colors.white,
    width: '90%',
    marginLeft:'5%',
    height: 50,
    position: 'relative',
    marginTop: 5,
    marginBottom: 3,
    justifyContent: 'center',
    borderRadius: 5,
    shadowColor: colors.shadow,
    shadowOffset: {width: 3, height: 3},
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 2,
  },
})



export default styles;
